In [1]:
#import libraries
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\sivak\anaconda3\lib\site-packages (2.1.2)
Requirement already satisfied: bleach in c:\users\sivak\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: jupytext in c:\users\sivak\anaconda3\lib\site-packages (from kaggle) (1.19.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.23 in c:\users\sivak\anaconda3\lib\site-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in c:\users\sivak\anaconda3\lib\site-packages (from kaggle) (24.1)
Requirement already satisfied: protobuf in c:\users\sivak\anaconda3\lib\site-packages (from kaggle) (5.29.4)
Requirement already satisfied: python-dateutil in c:\users\sivak\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\sivak\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in c:\users\sivak\anaconda3\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in c:\users\sivak\anaconda3\lib\site-packages (from kaggle) (4.66.5)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\sivak\anaconda3\lib\site-packages (from kaggle) (2.2.3)
Requirement already satisfied: six>=1.9.0 in c:\users\sivak\anaconda3\lib\site-packages (from bleach->kaggle) (1.16.0)
Requirement already satisfied: webencodings in c:\users\sivak\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\users\sivak\anaconda3\lib\site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\sivak\anaconda3\lib\site-packages (from jupytext->kaggle) (0.3.0)
Requirement already satisfied: nbformat in c:\users\sivak\anaconda3\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\users\sivak\anaconda3\lib\site-packages (from jupytext->kaggle) (6.0.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\sivak\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sivak\anaconda3\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sivak\anaconda3\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sivak\anaconda3\lib\site-packages (from requests->kaggle) (2024.12.14)
Requirement already satisfied: colorama in c:\users\sivak\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)
Requirement already satisfied: mdurl~=0.1 in c:\users\sivak\anaconda3\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\sivak\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\sivak\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (4.23.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\sivak\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\sivak\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\sivak\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\sivak\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\sivak\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\sivak\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.10.6)
Requirement already satisfied: platformdirs>=2.5 in c:\users\sivak\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\sivak\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (305.1)

In [3]:
import kaggle

#download dataset using  kaggle api
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [5]:
#extract file from zipfile
import zipfile
zip_ref=zipfile.ZipFile(r'C:\Users\sivak\orders.csv.zip')
zip_ref.extractall(r'C:\Users\sivak\orders_extracted')#extract file to dir
zip_ref.close() #close file

In [7]:
import os

os.listdir(r'C:\Users\sivak\orders_extracted')

['orders.csv']

In [19]:
# read data from file and handle null values
import pandas as pd

df = pd.read_csv(r'C:\Users\sivak\orders_extracted\orders.csv', na_values=['Not Available', 'unknown'])

df.head(20)
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [15]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [51]:
# rename column names,make them lower case and replace with underscore
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [57]:
# derive new columns discount,sale price and profit
#df.columns

df['discount']= df['list_price']*df['discount_percent']*.01
df['sale_price']=df['list_price']-df['discount']
df['profit']=df['sale_price']-df['cost_price']
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [63]:
# convert order date from object data type to datetime
#df.dtypes
pd.to_datetime(df['order_date'],format="%Y-%m-%d")

0      2023-03-01
1      2023-08-15
2      2023-01-10
3      2022-06-18
4      2022-07-13
          ...
9989   2023-02-18
9990   2023-03-17
9991   2022-08-07
9992   2022-11-19
9993   2022-07-17
Name: order_date, Length: 9994, dtype: datetime64[ns]

In [1]:
# drop cost price,list price,discount percentage columns
# df.drop(columns=['cost_price','list_price','discount_percent'],inplace=True)

In [81]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0

In [99]:
#load the data into sql server using replace option
import pandas as pd
import sqlalchemy as sal

In [113]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine(
    'mysql+pymysql://root:mysql123@localhost/retail_db'
)
conn=engine.connect()

In [123]:
df.to_sql(name='orders', con=engine, if_exists='append', index=False)

9994

In [116]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'quantity', 'discount', 'sale_price', 'profit'],
      dtype='object')